# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: event.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='event.proto',
  package='inkah',
  syntax='proto3',
  serialized_pb=_b('\n\x0b\x65vent.proto\x12\x05inkah\"v\n\x05\x45vent\x12\x0f\n\x07traceId\x18\x01 \x01(\t\x12\x0e\n\x06spanId\x18\x02 \x01(\t\x12\x14\n\x0cparentSpanId\x18\x03 \x01(\t\x12\x11\n\trequestId\x18\x04 \x01(\t\x12#\n\teventType\x18\x05 \x01(\x0e\x32\x10.inkah.EventType\"\x0f\n\rEventResponse*M\n\tEventType\x12\x0e\n\nSPAN_BEGIN\x10\x00\x12\x0c\n\x08SPAN_END\x10\x01\x12\x11\n\rREQUEST_BEGIN\x10\x02\x12\x0f\n\x0bREQUEST_END\x10\x03\x32>\n\x05Inkah\x12\x35\n\rRegisterEvent\x12\x0c.inkah.Event\x1a\x14.inkah.EventResponse\"\x00\x42\nZ\x08protobufb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_EVENTTYPE = _descriptor.EnumDescriptor(
  name='EventType',
  full_name='inkah.EventType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SPAN_BEGIN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SPAN_END', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REQUEST_BEGIN', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REQUEST_END', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=159,
  serialized_end=236,
)
_sym_db.RegisterEnumDescriptor(_EVENTTYPE)

EventType = enum_type_wrapper.EnumTypeWrapper(_EVENTTYPE)
SPAN_BEGIN = 0
SPAN_END = 1
REQUEST_BEGIN = 2
REQUEST_END = 3



_EVENT = _descriptor.Descriptor(
  name='Event',
  full_name='inkah.Event',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='traceId', full_name='inkah.Event.traceId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='spanId', full_name='inkah.Event.spanId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='parentSpanId', full_name='inkah.Event.parentSpanId', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='requestId', full_name='inkah.Event.requestId', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='eventType', full_name='inkah.Event.eventType', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=140,
)


_EVENTRESPONSE = _descriptor.Descriptor(
  name='EventResponse',
  full_name='inkah.EventResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=142,
  serialized_end=157,
)

_EVENT.fields_by_name['eventType'].enum_type = _EVENTTYPE
DESCRIPTOR.message_types_by_name['Event'] = _EVENT
DESCRIPTOR.message_types_by_name['EventResponse'] = _EVENTRESPONSE
DESCRIPTOR.enum_types_by_name['EventType'] = _EVENTTYPE

Event = _reflection.GeneratedProtocolMessageType('Event', (_message.Message,), dict(
  DESCRIPTOR = _EVENT,
  __module__ = 'event_pb2'
  # @@protoc_insertion_point(class_scope:inkah.Event)
  ))
_sym_db.RegisterMessage(Event)

EventResponse = _reflection.GeneratedProtocolMessageType('EventResponse', (_message.Message,), dict(
  DESCRIPTOR = _EVENTRESPONSE,
  __module__ = 'event_pb2'
  # @@protoc_insertion_point(class_scope:inkah.EventResponse)
  ))
_sym_db.RegisterMessage(EventResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z\010protobuf'))
try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces


  class InkahStub(object):

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.RegisterEvent = channel.unary_unary(
          '/inkah.Inkah/RegisterEvent',
          request_serializer=Event.SerializeToString,
          response_deserializer=EventResponse.FromString,
          )


  class InkahServicer(object):

    def RegisterEvent(self, request, context):
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_InkahServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'RegisterEvent': grpc.unary_unary_rpc_method_handler(
            servicer.RegisterEvent,
            request_deserializer=Event.FromString,
            response_serializer=EventResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'inkah.Inkah', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaInkahServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def RegisterEvent(self, request, context):
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaInkahStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def RegisterEvent(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      raise NotImplementedError()
    RegisterEvent.future = None


  def beta_create_Inkah_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('inkah.Inkah', 'RegisterEvent'): Event.FromString,
    }
    response_serializers = {
      ('inkah.Inkah', 'RegisterEvent'): EventResponse.SerializeToString,
    }
    method_implementations = {
      ('inkah.Inkah', 'RegisterEvent'): face_utilities.unary_unary_inline(servicer.RegisterEvent),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_Inkah_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('inkah.Inkah', 'RegisterEvent'): Event.SerializeToString,
    }
    response_deserializers = {
      ('inkah.Inkah', 'RegisterEvent'): EventResponse.FromString,
    }
    cardinalities = {
      'RegisterEvent': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'inkah.Inkah', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
