# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc
from grpc.framework.common import cardinality
from grpc.framework.interfaces.face import utilities as face_utilities

import event_pb2 as event__pb2


class InkahStub(object):

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.RegisterEvent = channel.unary_unary(
        '/inkah.Inkah/RegisterEvent',
        request_serializer=event__pb2.Event.SerializeToString,
        response_deserializer=event__pb2.EventResponse.FromString,
        )


class InkahServicer(object):

  def RegisterEvent(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_InkahServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'RegisterEvent': grpc.unary_unary_rpc_method_handler(
          servicer.RegisterEvent,
          request_deserializer=event__pb2.Event.FromString,
          response_serializer=event__pb2.EventResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'inkah.Inkah', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
